name: 'Tensorkube Deploy Action'
description: 'Deploy your prject using tensorkube'
inputs:
  gpus:
    description: 'Number of gpus to use'
    required: true
    default: 0
  gpu_type:
    description: 'Type of gpu to use'
    required: False
    default: null
  cpu:
    description: 'Number of cpus to use'
    required: true
    default: 100
  memory:
    description: 'Amount of memory to use'
    required: true
    default: 200
  min_scale:
    description: 'Minimum number of replicas'
    required: true
    default: 0
  max_scale:
    description: 'Maximum number of replicas'
    required: true
    default: 3
  env:
    description: 'Environment in which to deploy'
    required: true
    default: 'default'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gpus }}
    - ${{ inputs.gpu_type }}
    - ${{ inputs.cpu }}
    - ${{ inputs.memory }}
    - ${{ inputs.min_scale }}
    - ${{ inputs.max_scale }}
    - ${{ inputs.env }}
